=== MBalala55/OR/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/MBalala55/OR/refs/heads/main/knji%C5%BEnica.json",
  "type": "array",
  "title": "Knjižnica",
  "description": "Skup knjiga za otvoreno računarstvo",
  "items": {
    "type": "object",
    "title": "Knjiga",
    "description": "Objekt koji sadrži sve podatke o jednoj knjizi",
    "required": [
      "id",
      "isbn",
      "autor",
      "jezik",
      "naziv",
      "izdavac",
      "zanrovi",
      "primjerci",
      "broj_stranica",
      "godina_izdanja",
      "mjesto_izdanja"
    ],
    "properties": {
      "id": {
        "type": "number",
        "title": "ID",
        "description": "Jedinstveni identifikator knjige"
      },
      "isbn": {
        "type": "string",
        "title": "ISBN",
        "description": "Međunarodni standardni broj knjige"
      },
      "autor": {
        "type": "string",
        "title": "Autor",
        "description": "Ime i prezime autora knjige"
      },
      "jezik": {
        "type": "string",
        "title": "Jezik",
        "description": "Jezik na kojem je knjiga napisana"
      },
      "naziv": {
        "type": "string",
        "title": "Naziv",
        "description": "Naslov knjige"
      },
      "izdavac": {
        "type": "string",
        "title": "Izdavac",
        "description": "Naziv izdavačke kuće"
      },
      "zanrovi": {
        "type": "array",
        "title": "Žanrovi",
        "description": "Popis žanrova kojima knjiga pripada",
        "items": {
          "type": "string",
          "title": "Žanr",
          "description": "Jedan žanr"
        }
      },
      "primjerci": {
        "type": "array",
        "title": "Primjerci",
        "description": "Popis dostupnih primjeraka (broj primjerka i dostupnost)",
        "required": [
          "dostupnost",
          "broj_primjerka"
        ],
        "items": {
          "type": "object",
          "title": "Primjerak",
          "description": "Jedan primjerak knjige",
          "properties": {
            "dostupnost": {
              "type": "string",
              "title": "Dostupnost",
              "description": "Dostupnost pojedine knjige"
            },
            "broj_primjerka": {
              "type": "number",
              "title": "Broj primjerka",
              "description": "Broj primjerak pojedine knjige"
            }
          }
        }
      },
      "broj_stranica": {
        "type": "number",
        "title": "Broj stranica",
        "description": "Broj stranica pojedine knjige"
      },
      "godina_izdanja": {
        "type": "number",
        "title": "Godina izdanja",
        "description": "Godina izdanja pojedine knjige"
      },
      "mjesto_izdanja": {
        "type": "string",
        "title": "Mjesto izdanja",
        "description": "Mjesto izdanja pojedine knjige"
      }
    }
  }
}

=== MBalala55/OR/knjižnica.json
[
    {
        "id": 1,
        "isbn": "9789533284378",
        "autor": "William Shakespeare",
        "jezik": "hrvatski",
        "naziv": "Hamlet",
        "izdavac": "Bulaja naklada",
        "zanrovi": [
            "Tragedija",
            "Drama",
            "Klasična književnost"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            },
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 2
            }
        ],
        "broj_stranica": 180,
        "godina_izdanja": 2018,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 2,
        "isbn": "9789533280806",
        "autor": "Sophocles",
        "jezik": "hrvatski",
        "naziv": "Kralj Edip",
        "izdavac": "Bulaja naklada",
        "zanrovi": [
            "Tragedija",
            "Drama",
            "Klasična književnost"
        ],
        "primjerci": [
            {
                "dostupnost": "Nedostupna",
                "broj_primjerka": 1
            },
            {
                "dostupnost": "Nedostupna",
                "broj_primjerka": 2
            }
        ],
        "broj_stranica": 116,
        "godina_izdanja": 2011,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 3,
        "isbn": "9789533283197",
        "autor": "Lav Nikolaevič Tolstoj",
        "jezik": "hrvatski",
        "naziv": "Rat i mir",
        "izdavac": "Bulaja naklada",
        "zanrovi": [
            "Povijesni roman",
            "Epika",
            "Klasična književnost"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            },
            {
                "dostupnost": "Nedostupna",
                "broj_primjerka": 2
            }
        ],
        "broj_stranica": 915,
        "godina_izdanja": 2015,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 4,
        "isbn": "9789533200903",
        "autor": "George Orwell",
        "jezik": "hrvatski",
        "naziv": "1984.",
        "izdavac": "Šareni dućan",
        "zanrovi": [
            "Distopija",
            "Politički roman",
            "Znanstvena fantastika"
        ],
        "primjerci": [
            {
                "dostupnost": "Nedostupna",
                "broj_primjerka": 1
            },
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 2
            }
        ],
        "broj_stranica": 350,
        "godina_izdanja": 2015,
        "mjesto_izdanja": "Koprivnica"
    },
    {
        "id": 5,
        "isbn": "9789531961964",
        "autor": "Fedor Mihaljevič Dostoevskij",
        "jezik": "hrvatski",
        "naziv": "Zločin i kazna",
        "izdavac": "Mozaik knjiga",
        "zanrovi": [
            "Roman",
            "Psihološki roman",
            "Klasična književnost"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 476,
        "godina_izdanja": 2003,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 6,
        "isbn": "9789533412696",
        "autor": "Dante Alighieri",
        "jezik": "hrvatski",
        "naziv": "Božanstvena komedija: Raj",
        "izdavac": "Matica hrvatska",
        "zanrovi": [
            "Epika",
            "Alegorija",
            "Klasična književnost"
        ],
        "primjerci": [
            {
                "dostupnost": "Nedostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 686,
        "godina_izdanja": 2023,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 7,
        "isbn": "9789533421544",
        "autor": "John Ronald Reuel Tolkien",
        "jezik": "hrvatski",
        "naziv": "Gospodar prstenova: Prstenova družina",
        "izdavac": "Lumen izdavaštvo",
        "zanrovi": [
            "Fantastika",
            "Avantura",
            "Epika"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 516,
        "godina_izdanja": 2018,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 8,
        "isbn": "9789537160246",
        "autor": "George Orwell",
        "jezik": "hrvatski",
        "naziv": "Životinjska farma",
        "izdavac": "Globus media",
        "zanrovi": [
            "Satira",
            "Alegorija",
            "Povijesni roman"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 95,
        "godina_izdanja": 2004,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 9,
        "isbn": "9789531324977",
        "autor": "George Orwell",
        "jezik": "hrvatski",
        "naziv": "Životinjska farma",
        "izdavac": "Egmont",
        "zanrovi": [
            "Satira",
            "Alegorija",
            "Povijesni roman"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 136,
        "godina_izdanja": 2022,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 10,
        "isbn": "9789531324977",
        "autor": "George Orwell",
        "jezik": "hrvatski",
        "naziv": "Životinjska farma",
        "izdavac": "Egmont",
        "zanrovi": [
            "Satira",
            "Alegorija",
            "Povijesni roman"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 136,
        "godina_izdanja": 2024,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 11,
        "isbn": "9789533284309",
        "autor": "Jonathan Swift",
        "jezik": "hrvatski",
        "naziv": "Gulliverova putovanja",
        "izdavac": "Bulaja naklada",
        "zanrovi": [
            "Satira",
            "Fantastika",
            "Avantura"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 226,
        "godina_izdanja": 2018,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 12,
        "isbn": "9789530604076",
        "autor": "Jonathan Swift",
        "jezik": "hrvatski",
        "naziv": "Gulliverova putovanja",
        "izdavac": "Školska knjiga",
        "zanrovi": [
            "Satira",
            "Fantastika",
            "Avantura"
        ],
        "primjerci": [
            {
                "dostupnost": "Nedostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 153,
        "godina_izdanja": 1997,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 13,
        "isbn": "9789531920540",
        "autor": "Jonathan Swift",
        "jezik": "hrvatski",
        "naziv": "Gulliverova putovanja",
        "izdavac": "Zagrebačka stvarnost",
        "zanrovi": [
            "Satira",
            "Fantastika",
            "Avantura"
        ],
        "primjerci": [
            {
                "dostupnost": "Nedostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 112,
        "godina_izdanja": 2000,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 14,
        "isbn": "9789531410786",
        "autor": "Antoine de Saint-Exupéry",
        "jezik": "hrvatski",
        "naziv": "Mali princ",
        "izdavac": "Mozaik knjiga",
        "zanrovi": [
            "Fantastika",
            "Bajka",
            "Filozofska priča"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 89,
        "godina_izdanja": 2016,
        "mjesto_izdanja": "Zagreb"
    },
    {
        "id": 15,
        "isbn": "9789538313356",
        "autor": "Antoine de Saint-Exupéry",
        "jezik": "hrvatski",
        "naziv": "Mali princ",
        "izdavac": "Mala zvona",
        "zanrovi": [
            "Fantastika",
            "Bajka",
            "Filozofska priča"
        ],
        "primjerci": [
            {
                "dostupnost": "Dostupna",
                "broj_primjerka": 1
            }
        ],
        "broj_stranica": 60,
        "godina_izdanja": 2021,
        "mjesto_izdanja": "Zagreb"
    }
]
